# Generated by Django 4.2.8 on 2023-12-25 13:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0003_alter_soldtickets_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldtickets',
            name='cashier',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='soldtickets',
            name='sold_date',
            field=models.DateField(default=datetime.date(2023, 12, 25)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
